### ISSUE TITLE
Site fora do ar / muito instável

### ISSUE THREAD

**Issue by filipegarrett** [snowom/PossoLer#26]
Olá, tentando configurar o Posso Ler?, tenho encontrado dificuldades em rodar o site para pegar o script.

Seria possível oferecer uma forma diferente de obtenção do script e geração do hash? Mesmo que fosse mais manual como forma de opção para manter a ferramenta útil, mesmo que o site eventualmente pare de funcionar.

**Comment by lucasfigueiredolopes** [comment]
Também estou interessado em outra forma de geração do hash

**Comment by snowom** [comment]
Fala galera! Como vocês estão?

Acabei de escrever [uma issue](https://github.com/snowom/PossoLer/issues/27#issue-2493252825) explicando o que aconteceu com o projeto. Nela falo mais um pouco sobre o futuro do Posso Ler?

Porém, resumidamente, o que aconteceu foi que, denunciaram meu projeto, ele foi derrubado e minha conta suspensa :(
