### ISSUE TITLE
Script parou de funcionar am várias partes do site Responde AI

### ISSUE THREAD

**Issue by brenofaro** [snowom/PossoLer#3]
O script parou de funcionar em certas regiões do site como livros resolvidos, aulões e outras páginas. Pelo que eu percebi o script funciona quando entramos em um problema específico ou assunto de forma direta (link do google), mas quando tentamos acessar outras páginas do site logo vem a mensagem abaixo e impossibilita acessar outros conteudos:

![image](https://user-images.githubusercontent.com/94204696/232581661-ea59f93d-585d-4822-b22a-68a9cc087934.png)

**Comment by snowom** [comment]
Fala @brenofaro ! De boas mano?

Primeiramente, valeuzão por usar e apoiar o projeto! Isso é muito importante para mim!

Pô, acabei de ver aqui. Agradeço demais por ter relatado!
Esse novo bloqueio do Responde Aí me fez repensar em algumas coisas...

Se eles chegaram a esse ponto, de ter um trabalho para identificar quem está utilizando a extensão para bloquear o acesso ao site, é porque a extensão deve estar dando um prejuízo a eles. Entendo que a informação deve ser livre, mas como deixei claro no site do projeto desde o primeiro dia, meu intuito é ajudar e fornecer as pessoas fontes de informações e conhecimentos que sejam confiáveis, porém, sem prejudicar o jornal/site, pois eles também necessitam pagar seus empregados que, por sua vez, possuem suas contas para pagar e famílias para sustentar.
Pelo fato do Responde Aí não utilizar propagandas em seu site, usar a extensão acaba tendo um impacto maior no âmbito financeiro da empresa.

Pensando nesses pontos, planejo não continuar com o suporte da extensão ao Responde Aí. Sei que esse projeto ajuda/ajudou vários estudantes, ainda mais os de baixa renda que não tem condições para pagar um cursinho (já fui um) ou que vieram de escola pública e possuem uma base do ensino fundamental e médio muito fracas (também vim de escola pública e até hoje sofro por conta dessa base fraca), mas não posso ser egoísta a ponto de prejudicar consideravelmente uma empresa que também visa fornecer educação à estudantes (talvez pudessem seguir um caminho diferente? Talvez... Incluindo planos que uma pessoa em vulnerabilidade socioeconômica possa pagar?).

Ainda não é uma certeza que descontinuarei o suporte ao Responde Aí, mas é um caminho que parece estar bem perto.

**Comment by snowom** [comment]
> O script parou de funcionar em certas regiões do site como livros resolvidos, aulões e outras páginas. Pelo que eu percebi o script funciona quando entramos em um problema específico ou assunto de forma direta (link do google), mas quando tentamos acessar outras páginas do site logo vem a mensagem abaixo e impossibilita acessar outros conteudos:
> 
> ![image](https://user-images.githubusercontent.com/94204696/232581661-ea59f93d-585d-4822-b22a-68a9cc087934.png)

qwscxwqscwq

**Comment by snowom** [comment]
@brenofaro me desculpe, acabei fechando a issue sem querer kkkkkkkkkkk
