### ISSUE TITLE
Indisponibilidade do https://possoler.tech 

### ISSUE THREAD

**Issue by misaelbr** [snowom/PossoLer#4]
Buenas, estava evangelizando um colega  sobre como usar teu script, mas teu site tá retornando http 503. 
Espero que não tenha sido por ação de algum dos grandes portais.

Abraços,
Misael.

**Comment by deysebeatriz** [comment]
Oi, Misael! Tentei acessar ontem e também tive problemas, mas verifiquei agora e já voltou ao normal :)

**Comment by snowom** [comment]
Fala galera!
Tranquilos?

@misaelbr muito obrigado por avisar sobre a indisponibilidade do serviço! 
Direto o serviço de hospedagem dá dessas e derruba minha aplicação e nem avisam nada 😮‍💨

Como estou de férias e viajando, não consegui responder antes e nem ver se o site estava no ar ou não, só percebi a queda quando recebi o e-mail sobre essa issue 😪

Valeuzãoooo demais por terem avisado @deybeatriz @misaelbr !
Abraços!
