### ISSUE TITLE
Site fora do ar

### ISSUE THREAD

**Issue by abelcrvg** [snowom/PossoLer#5]
Aparentemente o site se encontra fora do ar, acabou o "projeto"?!

**Comment by snowom** [comment]
Fala @abelcrvg! Beleza mano?
Valeuzão por avisar a indisponibilidade do site. Essa serviço de hospedagem direto faz isso com meu projeto.
Sobre o projeto, ele não acabou, mas ultimamente ando muito ocupado com trabalho e faculdade, então não tenho tempo para atualizar e disponibilizar a nova versão da extensão 🙁

**Comment by abelcrvg** [comment]
De nada bro, seu projeto é excelente e sempre ajuda a gente que não tem essa grana pra poder usar esses sites, sempre utilizo o posso ler, admiro muito o seu trabalho.
A gente entende que você anda ocupado, sem problemas, boa sorte na sua carreira amigo!
